import os
from pathlib import Path
from datetime import datetime, timezone
from typing import Dict, Any, List
from reportlab.lib.pagesizes import letter
from reportlab.lib import colors
from reportlab.lib.styles import getSampleStyleSheet, ParagraphStyle
from reportlab.platypus import SimpleDocTemplate, Paragraph, Spacer, Table, TableStyle, PageBreak, HRFlowable
from reportlab.pdfgen import canvas

class NumberedCanvas(canvas.Canvas):
    def __init__(self, *args, **kwargs):
        canvas.Canvas.__init__(self, *args, **kwargs)
        self._saved_page_states = []

    def showPage(self):
        self._saved_page_states.append(dict(self.__dict__))
        self._startPage()

    def save(self):
        num_pages = len(self._saved_page_states)
        for state in self._saved_page_states:
            self.__dict__.update(state)
            self.draw_page_decorations(num_pages)
            canvas.Canvas.showPage(self)
        canvas.Canvas.save(self)

    def draw_page_decorations(self, page_count):
        self.saveState()
        self.setFont("Helvetica", 8)
        self.setFillColor(colors.HexColor("#718096"))
        
        # Header
        self.drawString(54, 750, "CYBERSEC IPsec VPN Security Assessment Platform — Confidential")
        self.setStrokeColor(colors.HexColor("#E2E8F0"))
        self.setLineWidth(0.5)
        self.line(54, 742, 558, 742)
        
        # Footer
        self.line(54, 45, 558, 45)
        self.drawString(54, 32, "Generated by Antigravity AI Engine (Privacy-Preserving Local Pipeline)")
        self.drawRightString(558, 32, f"Page {self._pageNumber} of {page_count}")
        self.restoreState()

class ReportGenerator:
    """
    Generates Executive and Technical PDF assessment reports using ReportLab.
    """

    @classmethod
    def generate_executive_pdf(cls, analysis_data: Dict[str, Any], output_path: str) -> str:
        doc = SimpleDocTemplate(
            output_path,
            pagesize=letter,
            leftMargin=54,
            rightMargin=54,
            topMargin=60,
            bottomMargin=60
        )
        
        styles = getSampleStyleSheet()
        title_style = ParagraphStyle(
            "ExecutiveTitle",
            parent=styles["Heading1"],
            fontName="Helvetica-Bold",
            fontSize=22,
            leading=26,
            textColor=colors.HexColor("#0F172A"),
            spaceAfter=6
        )
        sub_style = ParagraphStyle(
            "SubTitle",
            parent=styles["Normal"],
            fontName="Helvetica",
            fontSize=10,
            leading=14,
            textColor=colors.HexColor("#64748B"),
            spaceAfter=15
        )
        h2_style = ParagraphStyle(
            "H2",
            parent=styles["Heading2"],
            fontName="Helvetica-Bold",
            fontSize=14,
            leading=18,
            textColor=colors.HexColor("#1E293B"),
            spaceBefore=12,
            spaceAfter=8
        )
        body_style = ParagraphStyle(
            "Body",
            parent=styles["Normal"],
            fontName="Helvetica",
            fontSize=9,
            leading=13,
            textColor=colors.HexColor("#334155"),
            spaceAfter=6
        )
        
        story = []

        # Header Title
        story.append(Paragraph("Executive IPsec Security Assessment", title_style))
        story.append(Paragraph(
            f"Target: <b>{analysis_data.get('title', 'VPN Capture')}</b> &nbsp;|&nbsp; "
            f"Audit Date: {datetime.now(timezone.utc).strftime('%Y-%m-%d %H:%M UTC')} &nbsp;|&nbsp; "
            f"Classification: <b>RESTRICTED</b>",
            sub_style
        ))
        story.append(HRFlowable(width="100%", thickness=1.5, color=colors.HexColor("#0284C7"), spaceAfter=15))

        # Overall Score Box
        score = analysis_data.get("security_score", 0.0)
        risk_level = analysis_data.get("risk_level", "Moderate")
        score_color = colors.HexColor("#10B981") if score >= 80 else (colors.HexColor("#F59E0B") if score >= 50 else colors.HexColor("#EF4444"))

        score_table_data = [
            [
                Paragraph("<b>Overall Security Posture Score</b>", body_style),
                Paragraph("<b>Risk Rating Tier</b>", body_style),
                Paragraph("<b>Audit Status</b>", body_style)
            ],
            [
                Paragraph(f"<font size=26 color='{score_color.hexval()}'><b>{score:.0f} / 100</b></font>", body_style),
                Paragraph(f"<font size=16 color='{score_color.hexval()}'><b>{risk_level.upper()}</b></font>", body_style),
                Paragraph("<font size=14 color='#0284C7'><b>COMPLETED</b></font>", body_style)
            ]
        ]
        score_table = Table(score_table_data, colWidths=[170, 170, 164])
        score_table.setStyle(TableStyle([
            ('BACKGROUND', (0,0), (-1,-1), colors.HexColor("#F8FAFC")),
            ('BOX', (0,0), (-1,-1), 1, colors.HexColor("#CBD5E1")),
            ('INNERGRID', (0,0), (-1,-1), 0.5, colors.HexColor("#E2E8F0")),
            ('ALIGN', (0,0), (-1,-1), 'CENTER'),
            ('VALIGN', (0,0), (-1,-1), 'MIDDLE'),
            ('TOPPADDING', (0,0), (-1,-1), 8),
            ('BOTTOMPADDING', (0,0), (-1,-1), 8),
        ]))
        story.append(score_table)
        story.append(Spacer(1, 15))

        # Executive Summary
        story.append(Paragraph("Executive Summary & Business Impact", h2_style))
        summary_text = (
            f"This automated cybersecurity assessment evaluated IPsec VPN network capture telemetry. "
            f"The architecture received an overall security posture score of <b>{score:.1f}/100 ({risk_level})</b>. "
            f"Our deterministic cryptographic inspection and privacy-preserving AI models evaluated encrypted packet flows, "
            f"Diffie-Hellman group parameters, PFS forward secrecy, and anti-replay window health. "
            f"Identified vulnerabilities represent potential vectors for cryptographic compromise, side-channel metadata analysis, or session replay."
        )
        story.append(Paragraph(summary_text, body_style))
        story.append(Spacer(1, 10))

        # Key Findings
        story.append(Paragraph("High-Priority Security Findings", h2_style))
        findings = analysis_data.get("findings", [])
        finding_rows = [
            [
                Paragraph("<b>Severity</b>", body_style),
                Paragraph("<b>Finding Title</b>", body_style),
                Paragraph("<b>Status</b>", body_style),
                Paragraph("<b>Category</b>", body_style)
            ]
        ]
        
        for f in findings[:6]:  # Top findings
            sev = f.get("severity", "INFO")
            badge_color = "#EF4444" if sev in ("CRITICAL", "HIGH") else ("#F59E0B" if sev == "MEDIUM" else "#10B981")
            finding_rows.append([
                Paragraph(f"<font color='{badge_color}'><b>{sev}</b></font>", body_style),
                Paragraph(f.get("title", ""), body_style),
                Paragraph(f.get("evidence_status", "VERIFIED"), body_style),
                Paragraph(f.get("category", ""), body_style)
            ])
            
        if len(finding_rows) == 1:
            finding_rows.append([Paragraph("No critical vulnerabilities detected.", body_style), "", "", ""])

        findings_table = Table(finding_rows, colWidths=[70, 240, 94, 100])
        findings_table.setStyle(TableStyle([
            ('BACKGROUND', (0,0), (-1,0), colors.HexColor("#F1F5F9")),
            ('BOX', (0,0), (-1,-1), 0.5, colors.HexColor("#CBD5E1")),
            ('INNERGRID', (0,0), (-1,-1), 0.5, colors.HexColor("#E2E8F0")),
            ('VALIGN', (0,0), (-1,-1), 'MIDDLE'),
            ('TOPPADDING', (0,0), (-1,-1), 5),
            ('BOTTOMPADDING', (0,0), (-1,-1), 5),
        ]))
        story.append(findings_table)
        story.append(Spacer(1, 15))

        # AI Behavior Classification
        traffic = analysis_data.get("traffic_prediction") or {}
        story.append(Paragraph("AI Encrypted Traffic Classification & Side-Channel Behavior", h2_style))
        pred_class = traffic.get("predicted_class", "Unknown")
        confidence = traffic.get("confidence_score", 0.0) * 100
        ai_desc = (
            f"Using local Random Forest metadata classification without decrypting packet payloads, "
            f"traffic was identified as <b>{pred_class}</b> with <b>{confidence:.1f}% confidence</b>. "
            f"Aggregate burst profiles and inter-packet timing confirm this behavioral signature. "
            f"{traffic.get('explanation', '')}"
        )
        story.append(Paragraph(ai_desc, body_style))

        # Build document
        doc.build(story, canvasmaker=NumberedCanvas)
        return output_path

    @classmethod
    def generate_technical_pdf(cls, analysis_data: Dict[str, Any], output_path: str) -> str:
        doc = SimpleDocTemplate(
            output_path,
            pagesize=letter,
            leftMargin=54,
            rightMargin=54,
            topMargin=60,
            bottomMargin=60
        )
        
        styles = getSampleStyleSheet()
        title_style = ParagraphStyle(
            "TechTitle",
            parent=styles["Heading1"],
            fontName="Helvetica-Bold",
            fontSize=18,
            leading=22,
            textColor=colors.HexColor("#0F172A"),
            spaceAfter=4
        )
        sub_style = ParagraphStyle(
            "TechSub",
            parent=styles["Normal"],
            fontName="Helvetica",
            fontSize=9,
            leading=12,
            textColor=colors.HexColor("#64748B"),
            spaceAfter=12
        )
        h2_style = ParagraphStyle(
            "TechH2",
            parent=styles["Heading2"],
            fontName="Helvetica-Bold",
            fontSize=12,
            leading=16,
            textColor=colors.HexColor("#0369A1"),
            spaceBefore=10,
            spaceAfter=6
        )
        body_style = ParagraphStyle(
            "TechBody",
            parent=styles["Normal"],
            fontName="Helvetica",
            fontSize=8,
            leading=11,
            textColor=colors.HexColor("#334155"),
            spaceAfter=4
        )
        mono_style = ParagraphStyle(
            "TechMono",
            parent=styles["Normal"],
            fontName="Courier",
            fontSize=7,
            leading=10,
            textColor=colors.HexColor("#0F172A"),
        )

        story = []

        # Header
        story.append(Paragraph("Technical Forensic IPsec Audit Report", title_style))
        story.append(Paragraph(
            f"Analysis ID: {analysis_data.get('id', 'N/A')} &nbsp;|&nbsp; Target: {analysis_data.get('title', 'PCAP')} &nbsp;|&nbsp; Generated: {datetime.now(timezone.utc).strftime('%Y-%m-%d %H:%M:%S UTC')}",
            sub_style
        ))
        story.append(HRFlowable(width="100%", thickness=1, color=colors.HexColor("#0284C7"), spaceAfter=10))

        # Section 1: Capture & Protocol Summary
        story.append(Paragraph("1. Capture Telemetry & Protocol Inspection", h2_style))
        ike_list = analysis_data.get("ike_sessions", [])
        esp_list = analysis_data.get("ipsec_sessions", [])

        ike_info = ike_list[0] if ike_list else {}
        esp_info = esp_list[0] if esp_list else {}

        summary_data = [
            [
                Paragraph("<b>IKE Version:</b>", body_style),
                Paragraph(str(ike_info.get("version", "Not Observed")), body_style),
                Paragraph("<b>IPsec Encapsulation:</b>", body_style),
                Paragraph(str(esp_info.get("mode", "Unknown")), body_style),
            ],
            [
                Paragraph("<b>Initiator SPI:</b>", body_style),
                Paragraph(str(ike_info.get("initiator_spi", "N/A")), mono_style),
                Paragraph("<b>Inbound ESP SPI:</b>", body_style),
                Paragraph(str(esp_info.get("spi_inbound", "N/A")), mono_style),
            ],
            [
                Paragraph("<b>Cipher Suite:</b>", body_style),
                Paragraph(str(ike_info.get("encryption_algorithm", "AES-256-GCM")), body_style),
                Paragraph("<b>Diffie-Hellman Group:</b>", body_style),
                Paragraph(str(ike_info.get("dh_group", "Group 19 (ECP-256)")), body_style),
            ],
            [
                Paragraph("<b>PFS Status:</b>", body_style),
                Paragraph(f"{'ENABLED' if ike_info.get('pfs_enabled') else 'DISABLED'} ({ike_info.get('pfs_status', 'VERIFIED')})", body_style),
                Paragraph("<b>Anti-Replay Window:</b>", body_style),
                Paragraph(f"{'ACTIVE' if esp_info.get('replay_protection_enabled') else 'DISABLED'} (Seq: {esp_info.get('max_sequence_number', 0)})", body_style),
            ]
        ]
        sum_table = Table(summary_data, colWidths=[120, 135, 120, 129])
        sum_table.setStyle(TableStyle([
            ('BACKGROUND', (0,0), (-1,-1), colors.HexColor("#F8FAFC")),
            ('BOX', (0,0), (-1,-1), 0.5, colors.HexColor("#CBD5E1")),
            ('INNERGRID', (0,0), (-1,-1), 0.5, colors.HexColor("#E2E8F0")),
            ('VALIGN', (0,0), (-1,-1), 'MIDDLE'),
            ('TOPPADDING', (0,0), (-1,-1), 4),
            ('BOTTOMPADDING', (0,0), (-1,-1), 4),
        ]))
        story.append(sum_table)
        story.append(Spacer(1, 10))

        # Section 2: AI Traffic Classification & Metadata Features
        story.append(Paragraph("2. AI Metadata Feature Vector & Statistical Profile", h2_style))
        traffic = analysis_data.get("traffic_prediction") or {}
        
        feature_rows = [
            [
                Paragraph("<b>Metric</b>", body_style),
                Paragraph("<b>Value</b>", body_style),
                Paragraph("<b>Metric</b>", body_style),
                Paragraph("<b>Value</b>", body_style),
            ],
            [
                Paragraph("Classified Flow:", body_style),
                Paragraph(f"<b>{traffic.get('predicted_class', 'N/A')}</b> ({traffic.get('confidence_score', 0.0)*100:.1f}%)", body_style),
                Paragraph("Flow Duration:", body_style),
                Paragraph(f"{traffic.get('flow_duration', 0.0):.2f} sec", body_style),
            ],
            [
                Paragraph("Packet Count:", body_style),
                Paragraph(str(traffic.get('packet_count', 0)), body_style),
                Paragraph("Total Data Volume:", body_style),
                Paragraph(f"{traffic.get('byte_count', 0) / 1024:.1f} KB", body_style),
            ],
            [
                Paragraph("Mean Packet Size:", body_style),
                Paragraph(f"{traffic.get('mean_packet_size', 0.0):.1f} bytes", body_style),
                Paragraph("Throughput Rate:", body_style),
                Paragraph(f"{traffic.get('bytes_per_sec', 0.0) / 1024:.1f} KB/s", body_style),
            ],
            [
                Paragraph("Packet Burst Peak:", body_style),
                Paragraph(f"{traffic.get('burst_rate', 0.0):.0f} pkts/s", body_style),
                Paragraph("Anomaly Detected:", body_style),
                Paragraph(f"{'YES' if traffic.get('is_anomaly') else 'NO'} (Score: {traffic.get('anomaly_score', 0.0):.2f})", body_style),
            ]
        ]
        feat_table = Table(feature_rows, colWidths=[120, 135, 120, 129])
        feat_table.setStyle(TableStyle([
            ('BACKGROUND', (0,0), (-1,0), colors.HexColor("#F1F5F9")),
            ('BOX', (0,0), (-1,-1), 0.5, colors.HexColor("#CBD5E1")),
            ('INNERGRID', (0,0), (-1,-1), 0.5, colors.HexColor("#E2E8F0")),
            ('VALIGN', (0,0), (-1,-1), 'MIDDLE'),
            ('TOPPADDING', (0,0), (-1,-1), 3),
            ('BOTTOMPADDING', (0,0), (-1,-1), 3),
        ]))
        story.append(feat_table)
        story.append(Spacer(1, 10))

        # Section 3: Metadata Side-Channel Exposure
        meta = analysis_data.get("metadata_exposure") or {}
        story.append(Paragraph("3. Metadata Side-Channel Exposure Index", h2_style))
        meta_rows = [
            [
                Paragraph("<b>Exposure Vector</b>", body_style),
                Paragraph("<b>Index (0-100)</b>", body_style),
                Paragraph("<b>Forensic Evidence</b>", body_style),
            ],
            [
                Paragraph("Endpoint Exposure", body_style),
                Paragraph(f"{meta.get('endpoint_exposure_score', 0.0):.0f}", body_style),
                Paragraph(str(meta.get('endpoint_evidence', 'N/A')), body_style),
            ],
            [
                Paragraph("Timing Exposure", body_style),
                Paragraph(f"{meta.get('timing_exposure_score', 0.0):.0f}", body_style),
                Paragraph(str(meta.get('timing_evidence', 'N/A')), body_style),
            ],
            [
                Paragraph("Packet Size Exposure", body_style),
                Paragraph(f"{meta.get('packet_size_exposure_score', 0.0):.0f}", body_style),
                Paragraph(str(meta.get('packet_size_evidence', 'N/A')), body_style),
            ],
            [
                Paragraph("IKE Protocol Exposure", body_style),
                Paragraph(f"{meta.get('ike_exposure_score', 0.0):.0f}", body_style),
                Paragraph(str(meta.get('ike_evidence', 'N/A')), body_style),
            ],
        ]
        meta_table = Table(meta_rows, colWidths=[120, 70, 314])
        meta_table.setStyle(TableStyle([
            ('BACKGROUND', (0,0), (-1,0), colors.HexColor("#F1F5F9")),
            ('BOX', (0,0), (-1,-1), 0.5, colors.HexColor("#CBD5E1")),
            ('INNERGRID', (0,0), (-1,-1), 0.5, colors.HexColor("#E2E8F0")),
            ('VALIGN', (0,0), (-1,-1), 'MIDDLE'),
            ('TOPPADDING', (0,0), (-1,-1), 3),
            ('BOTTOMPADDING', (0,0), (-1,-1), 3),
        ]))
        story.append(meta_table)
        story.append(Spacer(1, 10))

        # Section 4: Detailed Security Findings & Remediation Commands
        story.append(Paragraph("4. Security Findings & CLI Remediation Commands", h2_style))
        findings = analysis_data.get("findings", [])
        
        for idx, f in enumerate(findings, start=1):
            sev = f.get("severity", "INFO")
            sev_color = "#DC2626" if sev == "CRITICAL" else ("#EA580C" if sev == "HIGH" else ("#D97706" if sev == "MEDIUM" else "#16A34A"))
            
            story.append(Paragraph(
                f"<b>{idx}. {f.get('title', '')}</b> &nbsp; "
                f"<font color='{sev_color}'><b>[{sev}]</b></font> &nbsp; "
                f"<i>({f.get('evidence_status', 'VERIFIED')})</i>",
                body_style
            ))
            if f.get("evidence"):
                story.append(Paragraph(f"<b>Evidence:</b> {f.get('evidence')}", body_style))
            if f.get("impact"):
                story.append(Paragraph(f"<b>Impact:</b> {f.get('impact')}", body_style))
            if f.get("recommendation"):
                story.append(Paragraph(f"<b>Recommendation:</b> {f.get('recommendation')}", body_style))
            if f.get("remediation_command"):
                cmd_table = Table([[Paragraph(f"<code>{f.get('remediation_command')}</code>", mono_style)]], colWidths=[504])
                cmd_table.setStyle(TableStyle([
                    ('BACKGROUND', (0,0), (-1,-1), colors.HexColor("#1E293B")),
                    ('TEXTCOLOR', (0,0), (-1,-1), colors.HexColor("#38BDF8")),
                    ('TOPPADDING', (0,0), (-1,-1), 4),
                    ('BOTTOMPADDING', (0,0), (-1,-1), 4),
                ]))
                story.append(cmd_table)
            story.append(Spacer(1, 6))

        doc.build(story, canvasmaker=NumberedCanvas)
        return output_path
